Repository payper-devs/payper-server, pull requests merged in 2025-08, with the labels that each got.

#110 [BUG #88]: 시스템 로그가 안 보이는 문제 해결
  build.gradle
  src/main/java/com/payper/domain/card/CardController.java
  src/main/java/com/payper/domain/card/CardService.java
  src/main/java/com/payper/domain/user/UserController.java
  src/main/java/com/payper/external/crawling/CardJsonCrawler.java
  src/main/java/com/payper/external/openai/OpenAISqlGenerator.java
  src/main/java/com/payper/global/auth/AuthController.java
  src/main/java/com/payper/global/auth/AuthService.java
  src/main/java/com/payper/global/auth/dto/KakaoLoginRequest.java
  src/main/java/com/payper/global/config/RootConfig.java
  src/main/java/com/payper/global/config/WebConfig.java
  src/main/java/com/payper/global/exception/GlobalExceptionHandler.java
  src/main/java/com/payper/global/security/config/SecurityConfig.java
  src/main/java/com/payper/global/security/filter/AuthenticationErrorFilter.java
  src/main/java/com/payper/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/payper/global/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/payper/global/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/payper/global/security/handler/LoginFailureHandler.java
  src/main/java/com/payper/global/security/handler/LoginSuccessHandler.java
  src/main/java/com/payper/global/security/service/CustomUserDetailsService.java
  src/main/java/com/payper/global/security/util/JsonResponse.java
  src/main/java/com/payper/global/test/TestController.java
  src/main/java/com/payper/global/test/TestService.java
  src/main/resources/com/payper/global/security/mapper/UserDetailsMapper.xml
  src/main/resources/log4j2.xml
  src/main/resources/logback.xml
  src/test/java/com/payper/global/test/TestServiceTest.java
Labels: 🐞 Bug

#117 [REFACTOR #116]: CardMapper -> card_company 수정
  src/main/java/com/payper/domain/card/dto/GradeResponse.java
  src/main/resources/com/payper/domain/card/CardMapper.xml
Labels: ⚒️ Refactor

#118 [FEATURE #111]: 회원 정보 조회
  build.gradle
  src/main/java/com/payper/domain/user/UserController.java
  src/main/java/com/payper/domain/user/UserMapper.java
  src/main/java/com/payper/domain/user/UserService.java
  src/main/java/com/payper/domain/user/dto/UserResponse.java
  src/main/java/com/payper/domain/user/exception/NoSuchUserException.java
  src/main/resources/com/payper/domain/user/UserMapper.xml
  src/main/resources/mybatis-config.xml
Labels: ✨ Feature

#122 [BUG #121]: 내 카드 조회 시 삭제된 카드 조회되는 문제 해결
  src/main/resources/com/payper/domain/card/CardMapper.xml
Labels: 🐞 Bug

#109 [REFACTOR #107]: Domain+@ -> DTO(Response) 생성 로직 리팩토링 및 domain 수정
  src/main/java/com/payper/domain/benefit/domain/BenefitGradeDiscount.java
  src/main/java/com/payper/domain/benefit/domain/Grade.java
  src/main/java/com/payper/domain/benefit/dto/BenefitGradeDiscountResponse.java
  src/main/java/com/payper/domain/benefit/dto/BenefitGradeResponse.java
  src/main/java/com/payper/domain/benefit/dto/BenefitResponse.java
  src/main/java/com/payper/domain/benefit/dto/GradeResponse.java
  src/main/java/com/payper/domain/card/domain/Card.java
  src/main/java/com/payper/domain/card/domain/CardCompany.java
  src/main/java/com/payper/domain/card/dto/CardCompanyResponse.java
  src/main/java/com/payper/domain/card/dto/CardResponse.java
  src/main/java/com/payper/domain/card/dto/GradeResponse.java
  src/main/java/com/payper/domain/category/dto/CategoryResponse.java
  src/main/java/com/payper/domain/category/dto/PartnerResponse.java
  src/main/java/com/payper/domain/partner/domain/Partner.java
  src/main/java/com/payper/domain/partner/dto/PartnerResponse.java
  src/main/java/com/payper/domain/user/domain/UserCard.java
  src/main/java/com/payper/domain/user/dto/UserResponse.java
  src/main/java/com/payper/global/exception/CustomIllegalArgumentException.java
  src/main/resources/com/payper/domain/card/CardMapper.xml
Labels: ⚒️ Refactor, ✨ Feature

#125 [FEATURE #101]: 가맹점 위치 정보 정제
  src/main/java/com/payper/domain/partner/PartnerController.java
  src/main/java/com/payper/domain/partner/PartnerService.java
  src/main/java/com/payper/domain/partner/dto/PartnerKeywordSearchResponse.java
  src/main/java/com/payper/global/security/config/SecurityConfig.java
  src/main/java/com/payper/global/security/util/JwtProcessor.java
Labels: ✨ Feature

#131 [FEATURE #81]: 로그인 시 RefreshToken 함께 발급
  src/main/java/com/payper/global/auth/AuthController.java
  src/main/java/com/payper/global/auth/AuthService.java
  src/main/java/com/payper/global/security/util/JwtProcessor.java
Labels: ✨ Feature

#132 [FEATURE #130]: 토큰 재발급 API 구현
  src/main/java/com/payper/global/auth/AuthController.java
  src/main/java/com/payper/global/auth/AuthService.java
  src/main/java/com/payper/global/auth/dto/TokenResponse.java
  src/main/java/com/payper/global/auth/exception/InvalidRefreshTokenException.java
  src/main/java/com/payper/global/handler/AuthExceptionHandler.java
Labels: ✨ Feature, 🔒 Security

#135 [REFACTOR #124]: 수정된 응답 객체 및 ERD 기반 CardMapper 수정
  src/main/java/com/payper/domain/card/CardController.java
  src/main/resources/com/payper/domain/card/CardMapper.xml
Labels: ⚒️ Refactor

#136 [FEATURE #127]: 로그아웃 API 구현
  src/main/java/com/payper/global/auth/AuthController.java
  src/main/java/com/payper/global/auth/AuthService.java
Labels: ✨ Feature, 🔒 Security

#141 [FEATURE #128]: 내 혜택 정보 정제
  gradlew
  src/main/java/com/payper/domain/card/CardMapper.java
  src/main/java/com/payper/domain/partner/PartnerController.java
  src/main/java/com/payper/domain/partner/PartnerService.java
  src/main/java/com/payper/domain/partner/dto/PartnerKeywordSearchResponse.java
  src/main/java/com/payper/domain/partner/dto/PartnerResponse.java
  src/main/java/com/payper/external/crawling/CardJsonCrawler.java
  src/main/resources/com/payper/domain/card/CardMapper.xml
Labels: ✨ Feature

#154 [REFACTOR #153]: CardBenefitCleaner에서 grade 관련 수정
  src/main/java/com/payper/external/crawling/CardBenefitCleaner.java
Labels: ✨ Feature

#146 [FEATURE #145]: 카드 삭제 API 구현
  src/main/java/com/payper/domain/card/CardController.java
  src/main/java/com/payper/domain/card/CardMapper.java
  src/main/java/com/payper/domain/card/CardService.java
  src/main/resources/com/payper/domain/card/CardMapper.xml
Labels: ✨ Feature

#162 [REFACTOR #160]: 내 카드 삭제
  src/main/java/com/payper/domain/card/CardService.java
  src/main/java/com/payper/domain/card/exception/AlreadyDeletedUserCardException.java
  ãUserService로
Labels: ⚒️ Refactor

#155 [FEATURE #144]: 혜택 수정 API 구현
  src/main/java/com/payper/domain/benefit/BenefitController.java
  src/main/java/com/payper/domain/benefit/BenefitMapper.java
  src/main/java/com/payper/domain/benefit/BenefitService.java
  src/main/java/com/payper/domain/benefit/dto/request/CreateBenefitRequest.java
  src/main/java/com/payper/domain/benefit/dto/request/UpdateBenefitRequest.java
  src/main/java/com/payper/domain/benefit/dto/response/BenefitGradeDiscountResponse.java
  src/main/java/com/payper/domain/benefit/dto/response/BenefitResponse.java
  src/main/java/com/payper/domain/benefit/dto/response/BenefitsResponse.java
  src/main/java/com/payper/domain/benefit/dto/response/GradeResponse.java
  src/main/java/com/payper/domain/benefit/exception/BenefitNotFoundException.java
  src/main/java/com/payper/domain/card/CardMapper.java
  src/main/java/com/payper/domain/card/CardService.java
  src/main/java/com/payper/domain/card/dto/CardResponse.java
  src/main/resources/com/payper/domain/benefit/BenefitMapper.xml
  src/main/resources/com/payper/domain/card/CardMapper.xml
Labels: ✨ Feature

#164 [FEATURE #150]: 카드 정보 수정 API 구현
  src/main/java/com/payper/domain/card/CardController.java
  src/main/java/com/payper/domain/card/CardMapper.java
  src/main/java/com/payper/domain/card/CardService.java
  src/main/java/com/payper/domain/card/dto/UpdateCardRequest.java
  src/main/java/com/payper/domain/card/exception/CardRegisterationFailedException.java
  src/main/java/com/payper/domain/card/exception/CardUpdateFailedException.java
  src/main/resources/com/payper/domain/card/CardMapper.xml
Labels: ✨ Feature

#168 [REFACTOR #167]: PartnerResponse 수정
  src/main/java/com/payper/domain/category/CategoryMapper.java
  src/main/java/com/payper/domain/partner/PartnerMapper.java
  src/main/java/com/payper/domain/partner/PartnerService.java
  src/main/java/com/payper/domain/partner/dto/PartnerResponse.java
  src/main/java/com/payper/domain/partner/dto/PartnerTempDto.java
  src/main/resources/com/payper/domain/category/CategoryMapper.xml
  src/main/resources/com/payper/domain/partner/PartnerMapper.xml
  src/main/resources/sql/data/user.sql
Labels: ⚒️ Refactor

#177 [DEVOPS #161]: Dockerfile 생성
  Dockerfile
  build.gradle
Labels: 🐳 DevOps

#183 [DEVOPS #179]: docker-compose & Github Actions CI/CD workflow 파일 작성
  .github/workflows/deploy.yml
  .gitignore
  docker-compose.yml
  src/main/java/com/payper/global/config/RootConfig.java
  src/main/resources/application.properties
Labels: 🐳 DevOps

#197 [FEATURE #195]: 크롤링한 정보를 토대로 SQL문 생성 - 실적등급
  src/main/java/com/payper/domain/benefit/BenefitMapper.java
  src/main/java/com/payper/external/crawling/config/CardDataMatcher.java
  src/main/java/com/payper/external/crawling/service/CardSaveService.java
  src/main/java/com/payper/external/crawling/service/CrawlingService.java
  src/main/resources/com/payper/domain/benefit/BenefitMapper.xml
Labels: ✨ Feature

#202 [FEATURE #201]: 크롤링한 정보를 토대로 SQL문 생성 - 혜택
  src/main/java/com/payper/domain/benefit/dto/request/CreateBenefitRequest.java
  src/main/java/com/payper/external/crawling/config/CardDataMatcher.java
  src/main/java/com/payper/external/crawling/service/CardSaveService.java
  src/main/resources/com/payper/domain/benefit/BenefitMapper.xml
Labels: ✨ Feature

#204 [FEATURE #203]: 크롤링한 정보를 토대로 SQL문 생성 - 카테고리
  src/main/java/com/payper/domain/category/CategoryMapper.java
  src/main/java/com/payper/domain/category/dto/RegisterCategoryRequest.java
  src/main/java/com/payper/external/crawling/config/CardDataMatcher.java
  src/main/java/com/payper/external/crawling/service/CardSaveService.java
  src/main/resources/com/payper/domain/category/CategoryMapper.xml
Labels: ✨ Feature

#208 [FEATURE #206]: 크롤링한 정보를 토대로 SQL문 생성 - 혜택_카테고리
  src/main/java/com/payper/domain/category/CategoryMapper.java
  src/main/java/com/payper/external/crawling/service/CardSaveService.java
  src/main/resources/com/payper/domain/category/CategoryMapper.xml
Labels: ✨ Feature

#212 [REFACTOR #211]: CODEF 유저 인증 수정
  src/main/java/com/payper/domain/user/UserMapper.java
  src/main/java/com/payper/domain/user/UserService.java
  src/main/java/com/payper/external/codef/CodefController.java
  src/main/java/com/payper/external/codef/CodefService.java
  src/main/java/com/payper/external/codef/exception/AlreadyLinkedCodefAccountException.java
  src/main/java/com/payper/external/codef/exception/CodefAccountNotLinkedException.java
  src/main/java/com/payper/external/codef/exception/CodefResponseFailureException.java
  src/main/java/com/payper/external/codef/exception/ConnectedIdUpdateFailedException.java
  src/main/java/com/payper/external/codef/exception/EncryptPasswordFailedException.java
  src/main/java/com/payper/external/codef/exception/MismatchedConnectedIdException.java
  src/main/java/com/payper/external/codef/exception/MissingConnectedIdInCodefResponseException.java
  src/main/resources/com/payper/domain/user/UserMapper.xml
Labels: ⚒️ Refactor

#216 [REFACTOR #213]: 파트너 및 카드 응답 객체 수정
  src/main/java/com/payper/domain/category/CategoryMapper.java
  src/main/java/com/payper/domain/partner/PartnerService.java
  src/main/java/com/payper/domain/partner/dto/PartnerResponse.java
  src/main/resources/com/payper/domain/category/CategoryMapper.xml
Labels: ⚒️ Refactor

#218 [REFACTOR #214]: 현재까지의 SQL문으로 크롤링 시도
  src/main/java/com/payper/external/crawling/CrawlAndSaveController.java
  src/main/java/com/payper/external/crawling/service/CardSaveService.java
  src/main/java/com/payper/external/crawling/service/CrawlingService.java
  src/main/java/com/payper/external/crawling/service/sub/CardGradeCleanService.java
  src/main/java/com/payper/external/crawling/service/sub/CardJsonExtractService.java
  src/main/resources/sql/schema/V2_schema.sql
Labels: ⚒️ Refactor

#220 [REFACTOR #215]: Secret Key 외부로 export
  .github/workflows/deploy.yml
  .gitignore
  src/main/java/com/payper/domain/user/UserMapper.java
  src/main/java/com/payper/domain/user/dto/CreateUserRequest.java
  src/main/java/com/payper/global/auth/AuthService.java
  src/main/java/com/payper/global/auth/exception/UserCreationFailedException.java
  src/main/java/com/payper/global/config/RootConfig.java
  src/main/java/com/payper/global/security/util/JwtProcessor.java
  src/main/resources/application.properties
  src/main/resources/com/payper/domain/user/UserMapper.xml
Labels: ⚒️ Refactor

#222 [FEATURE #221]: 크롤링한 정보를 토대로 SQL문 생성 - 파트너
  src/main/java/com/payper/domain/partner/PartnerMapper.java
  src/main/java/com/payper/domain/partner/dto/RegisterPartnerRequest.java
  src/main/java/com/payper/external/crawling/config/CardDataMatcher.java
  src/main/java/com/payper/external/crawling/service/CardSaveService.java
  src/main/java/com/payper/external/crawling/service/sub/CardBenefitCleanService.java
  src/main/java/com/payper/external/crawling/service/sub/OpenAIExtractPartnerService.java
  src/main/resources/com/payper/domain/partner/PartnerMapper.xml
  src/main/resources/sql/schema/V2_schema.sql
Labels: ✨ Feature

#230 [REFACTOR #227]: ERD 수정에 따른 schema.sql 수정
  src/main/resources/sql/schema/V3_schema.sql
Labels: ⚒️ Refactor

#232 [REFACTOR #229]: ERD 수정에 따른 Category, Partner, User 수정
  src/main/java/com/payper/domain/category/domain/Category.java
  src/main/java/com/payper/domain/partner/PartnerMapper.java
  src/main/java/com/payper/domain/partner/PartnerService.java
  src/main/java/com/payper/domain/user/UserMapper.java
  src/main/java/com/payper/domain/user/UserService.java
  src/main/java/com/payper/domain/user/dto/UserResponse.java
  src/main/java/com/payper/external/crawling/service/CardSaveService.java
  src/main/java/com/payper/global/security/service/CustomUserDetailsService.java
  src/main/resources/com/payper/domain/partner/PartnerMapper.xml
  src/main/resources/com/payper/domain/user/UserMapper.xml
  src/main/resources/mybatis-config.xml
Labels: ⚒️ Refactor

#226 [REFACTOR #224]: Card soft delete 재정의
  src/main/java/com/payper/domain/benefit/BenefitService.java
  src/main/java/com/payper/domain/benefit/exception/GradeDeletionFailedException.java
  src/main/java/com/payper/domain/card/CardController.java
  src/main/java/com/payper/domain/card/CardMapper.java
  src/main/java/com/payper/domain/card/CardService.java
  src/main/java/com/payper/domain/partner/PartnerService.java
  src/main/java/com/payper/domain/user/exception/UserCardDeletionFailedException.java
  src/main/java/com/payper/external/crawling/service/CardSaveService.java
  src/main/resources/com/payper/domain/card/CardMapper.xml
Labels: ⚒️ Refactor

#233 [FEATURE #231]: 카테고리 및 가맹점 특정지어 db insert
  src/main/resources/sql/data/V3_category_partner.sql
  src/main/resources/sql/schema/V3_schema.sql
Labels: ✨ Feature

#235 [REFACTOR #228]: ERD 수정에 따른 DOMAIN, DTO, 메서드명
  src/main/java/com/payper/domain/benefit/BenefitMapper.java
  src/main/java/com/payper/domain/benefit/BenefitService.java
  src/main/java/com/payper/domain/benefit/domain/Benefit.java
  src/main/java/com/payper/domain/benefit/domain/BenefitGradeDiscount.java
  src/main/java/com/payper/domain/benefit/domain/Grade.java
  src/main/java/com/payper/domain/benefit/dto/response/BenefitGradeDiscountResponse.java
  src/main/java/com/payper/domain/benefit/dto/response/BenefitResponse.java
  src/main/java/com/payper/domain/benefit/dto/response/GradeResponse.java
  src/main/java/com/payper/domain/benefit/exception/GradeDeletionFailedException.java
  src/main/java/com/payper/domain/card/CardMapper.java
  src/main/java/com/payper/domain/card/CardService.java
  src/main/java/com/payper/domain/card/domain/Card.java
  src/main/java/com/payper/domain/card/dto/CardResponse.java
  src/main/java/com/payper/domain/category/CategoryMapper.java
  src/main/java/com/payper/external/crawling/service/CardSaveService.java
  src/main/resources/com/payper/domain/benefit/BenefitMapper.xml
  src/main/resources/com/payper/domain/card/CardMapper.xml
  src/main/resources/com/payper/domain/category/CategoryMapper.xml
Labels: ⚒️ Refactor

#236 [FEATURE #182]: CODEF 내 소유 카드 정보 DB 등록
  build.gradle
  src/main/java/com/payper/domain/card/CardService.java
  src/main/java/com/payper/external/codef/CodefController.java
  src/main/java/com/payper/external/codef/CodefMapper.java
  src/main/java/com/payper/external/codef/CodefService.java
  src/main/java/com/payper/external/codef/dto/FilteredCardByCompanyName.java
  src/main/java/com/payper/external/codef/dto/response/CardSimilarityResponse.java
  src/main/java/com/payper/external/codef/util/CardSimilarityService.java
  src/main/java/com/payper/external/codef/util/CardVectorUtils.java
  src/main/java/com/payper/external/codef/util/CosineSimilarity.java
  src/main/java/com/payper/external/codef/util/KoreanTokenizer.java
  src/main/java/com/payper/external/codef/util/OrganizationCode.java
  src/main/resources/com/payper/external/codef/CodefMapper.xml
  src/main/resources/mybatis-config.xml
Labels: ✨ Feature

#237 [REFACTOR #225]: 데이터 크롤링 및 저장 재진행
  src/main/java/com/payper/domain/benefit/BenefitMapper.java
  src/main/java/com/payper/domain/card/dto/RegisterCardRequest.java
  src/main/java/com/payper/domain/category/CategoryMapper.java
  src/main/java/com/payper/domain/category/dto/RegisterCategoryRequest.java
  src/main/java/com/payper/domain/partner/PartnerMapper.java
  src/main/java/com/payper/domain/partner/dto/RegisterPartnerRequest.java
  src/main/java/com/payper/external/crawling/config/CardDataMatcher.java
  src/main/java/com/payper/external/crawling/config/partnerSynonyms.java
  src/main/java/com/payper/external/crawling/dto/Benefit.java
  src/main/java/com/payper/external/crawling/dto/CardData.java
  src/main/java/com/payper/external/crawling/dto/Discount.java
  src/main/java/com/payper/external/crawling/dto/Grade.java
  src/main/java/com/payper/external/crawling/service/CardSaveService.java
  src/main/java/com/payper/external/crawling/service/CrawlingService.java
  src/main/java/com/payper/external/crawling/service/sub/BenefitToCategoryAndPartnerService.java
  src/main/java/com/payper/external/crawling/service/sub/CardBenefitCleanService.java
  src/main/java/com/payper/external/crawling/service/sub/CardGradeCleanService.java
  src/main/java/com/payper/external/crawling/service/sub/CardJsonExtractService.java
  src/main/java/com/payper/external/crawling/service/sub/OpenAIExtractPartnerAndCategoryService.java
  src/main/java/com/payper/external/crawling/service/sub/OpenAIExtractPartnerService.java
  src/main/resources/com/payper/domain/benefit/BenefitMapper.xml
  src/main/resources/com/payper/domain/card/CardMapper.xml
  src/main/resources/com/payper/domain/category/CategoryMapper.xml
  src/main/resources/com/payper/domain/partner/PartnerMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/resources/sql/data/V3_category_partner.sql
  src/main/resources/sql/schema/V3_schema.sql
Labels: ⚒️ Refactor

#243 [BUG #242]: 회원 탈퇴 API 에러
  src/main/resources/com/payper/domain/user/UserMapper.xml
Labels: 🐞 Bug

#251 [BUG #250]: 카카오 로그인 시 User 중복 생성 문제
  src/main/resources/com/payper/domain/user/UserMapper.xml
Labels: 🐞 Bug

#253 [BUG #252]: 카카오 로그인 버그 해결
  src/main/java/com/payper/global/auth/AuthService.java
Labels: 🐞 Bug

#255 [SECURITY #254]: /api/crawl 엔드포인트 인가 허용
  src/main/java/com/payper/global/security/config/SecurityConfig.java
Labels: 🔒 Security

#262 [FEATURE #261]: 사용자 및 위치 기반으로 가까운 가맹점 & 카드 정보 받아오기
  .gitignore
  build.gradle
  src/main/java/com/payper/domain/card/CardMapper.java
  src/main/java/com/payper/domain/partner/PartnerService.java
  src/main/java/com/payper/global/notification/NotificationController.java
  src/main/java/com/payper/global/notification/config/FcmConfig.java
  src/main/java/com/payper/global/notification/dto/NotificationResponse.java
  src/main/java/com/payper/global/notification/service/FcmService.java
  src/main/java/com/payper/global/notification/service/NotificationService.java
  src/main/java/com/payper/global/security/config/SecurityConfig.java
  src/main/resources/com/payper/domain/card/CardMapper.xml
Labels: ✨ Feature

#265 [REFACTOR #260]: 보유 카드 조회 시 이미 등록된 카드에 대해 에러 발생 수정
  src/main/java/com/payper/external/codef/CodefController.java
  src/main/java/com/payper/external/codef/CodefService.java
  src/main/java/com/payper/external/codef/CodefService2.java
  src/main/java/com/payper/external/codef/dto/CardRegistrationResult.java
  src/main/java/com/payper/external/codef/dto/RegistrationStatus.java
  src/main/java/com/payper/external/codef/dto/output/CodefStandardResponse.java
  src/main/java/com/payper/external/codef/dto/response/CardSimilarityResponse.java
  src/main/java/com/payper/external/codef/dto/response/MyCardListResponse.java
  src/main/java/com/payper/external/codef/util/CardSimilarityService2.java
  src/main/java/com/payper/external/codef/util/KoreanTokenizer2.java
  src/main/java/com/payper/external/codef/util/MatchType.java
  src/main/resources/com/payper/domain/card/CardMapper.xml
  src/main/resources/sql/schema/V3_schema.sql
Labels: ⚒️ Refactor

#275 [DEVOPS #274]: firebase 관련 데이터 .env에 추가
  .github/workflows/deploy.yml
Labels: 🐳 DevOps

#280 [DEVOPS #279]: PrometheusController 수정
  src/main/java/com/payper/global/metric/PrometheusController.java
Labels: 🐳 DevOps

#270 [FEATURE #269]: 불러온 사용 내역을 DB에 저장용 매퍼, domain
  src/main/java/com/payper/domain/card/CardMapper.java
  src/main/java/com/payper/domain/partner/domain/Partner.java
  src/main/java/com/payper/domain/user/UserCardMapper.java
  src/main/java/com/payper/domain/user/UserCardTransactionMapper.java
  src/main/java/com/payper/domain/user/UserCardTransactionService.java
  src/main/java/com/payper/domain/user/domain/UserCard.java
  src/main/java/com/payper/domain/user/domain/UserCardMonthTransaction.java
  src/main/java/com/payper/domain/user/domain/UserCardTransaction.java
  src/main/java/com/payper/domain/user/exception/UserCardTransactionSaveFailedException.java
  src/main/java/com/payper/external/codef/dto/response/ApprovalListResponse.java
  src/main/resources/com/payper/domain/card/CardMapper.xml
  src/main/resources/com/payper/domain/user/UserCardMapper.xml
  src/main/resources/com/payper/domain/user/UserCardTransactionMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/resources/sql/schema/V3_schema.sql
Labels: ✨ Feature

#283 [REFACTOR #282]: CODEF 승인내역 저장 로직 및 매핑 구조 개선
  src/main/java/com/payper/domain/card/CardMapper.java
  src/main/java/com/payper/domain/user/UserCardMapper.java
  src/main/java/com/payper/domain/user/UserCardTransactionMapper.java
  src/main/java/com/payper/domain/user/UserCardTransactionService.java
  src/main/java/com/payper/domain/user/domain/User.java
  src/main/java/com/payper/domain/user/domain/UserCardTransaction.java
  src/main/java/com/payper/external/codef/CodefService.java
  src/main/java/com/payper/external/crawling/config/partnerSynonyms.java
  src/main/resources/com/payper/domain/card/CardMapper.xml
  src/main/resources/com/payper/domain/user/UserCardMapper.xml
  src/main/resources/com/payper/domain/user/UserCardTransactionMapper.xml
  src/main/resources/sql/schema/V3_schema.sql
Labels: ⚒️ Refactor

#286 [BUG #284]: 내 카드 삭제 후 재등록 안됨
  src/main/java/com/payper/domain/card/CardController.java
  src/main/java/com/payper/domain/card/CardMapper.java
  src/main/java/com/payper/domain/card/CardService.java
  src/main/resources/com/payper/domain/card/CardMapper.xml
  src/main/resources/sql/schema/V3_schema.sql
Labels: 🐞 Bug

#290 [BUG #288]: connected id 발급 과정에서 프론트 연동 시 오류 발생
  src/main/java/com/payper/external/codef/CodefService.java
Labels: 🐞 Bug

#289 [DEVOPS #287]: HTTP 관련 메트릭 빈 추가
  src/main/java/com/payper/global/config/ServletConfig.java
  src/main/java/com/payper/global/metric/HttpMetricsFilter.java
  src/main/java/com/payper/global/metric/HttpTraceMetrics.java
  src/main/java/com/payper/global/metric/MetricConfig.java
  src/main/java/com/payper/global/metric/MetricsInterceptor.java
Labels: 🐳 DevOps

#295 [BUG #294]: 요청 바디 컨트롤러 수정
  src/main/java/com/payper/global/notification/NotificationController.java
Labels: 🐞 Bug

#306 [REFACTOR #305]: 최적화 전에, 성능 측정을 위한 card search 관련 매퍼 리팩토링 기준점. usercard 관련 칼럼 조회 제거
  src/main/resources/com/payper/domain/card/SearchMapper.xml
Labels: ⚒️ Refactor

#307 [DEVOPS #301]: ELK 로그 모니터링 시스템 구성
  docker-compose.yml
  infra/app/default.conf
  infra/app/filebeat.yml
  infra/monitor/docker-compose.yml
  infra/monitor/prometheus.yml
  prometheus/prometheus.yml
  src/main/resources/logback.xml
Labels: 🐳 DevOps

#309 [DEVOPS #308]: Filebeat 관련 docker-compose.yml 수정
  build.gradle
  docker-compose.yml
  src/main/resources/logback.xml
Labels: 🐳 DevOps

#312 [REFACTOR #305]: 최적화 전에, 성능 측정을 위한 card search 관련 매퍼 리팩토링 기준점 최종
  src/main/java/com/payper/domain/card/SearchOptions.java
  src/main/resources/com/payper/domain/card/SearchMapper.xml
Labels: ⚒️ Refactor

#318 [TEST #313]: 부하 테스트를 위한 목데이터 생성 코드 작성
  src/main/resources/sql/seed/example.sql
  src/main/resources/sql/seed/procedure.sql
Labels: 🧪 Test

#319 [FEATURE]: 시중 카드 검색 슬라이싱 기능 구현 #314
  src/main/java/com/payper/domain/benefit/BenefitService.java
  src/main/java/com/payper/domain/card/CardController.java
  src/main/java/com/payper/domain/card/SearchOptions.java
  src/main/java/com/payper/domain/card/dto/CardsResponse.java
  src/main/java/com/payper/domain/card/mapper/CardMapper.java
  src/main/java/com/payper/domain/card/mapper/SearchMapper.java
  src/main/java/com/payper/domain/card/service/CardService.java
  src/main/java/com/payper/domain/card/service/SearchService.java
  src/main/java/com/payper/domain/partner/PartnerService.java
  src/main/java/com/payper/domain/user/UserCardTransactionService.java
  src/main/java/com/payper/external/codef/CodefService.java
  src/main/java/com/payper/external/codef/CodefService2.java
  src/main/java/com/payper/external/crawling/service/CardSaveService.java
  src/main/java/com/payper/global/notification/service/NotificationService.java
  src/main/resources/com/payper/domain/card/mapper/CardMapper.xml
  src/main/resources/com/payper/domain/card/mapper/SearchMapper.xml
Labels: ✨ Feature

#321 [FEATURE]: 시중 카드 검색 슬라이싱 기능 구현 #314
  src/main/java/com/payper/domain/card/service/SearchService.java
Labels: ⚒️ Refactor

#323 [REFACTOR #322]: 시중 카드 가맹점 검색 수정
  src/main/java/com/payper/domain/partner/PartnerController.java
  src/main/java/com/payper/domain/partner/PartnerService.java
  src/main/java/com/payper/domain/partner/dto/PartnerResponse.java
Labels: ⚒️ Refactor

#325 [FEATURE #320]: 사용자의 소비 패턴으로 소비습관 분석
  src/main/java/com/payper/domain/user/UserCardTransactionMapper.java
  src/main/java/com/payper/domain/user/UserController.java
  src/main/java/com/payper/domain/user/UserService.java
  src/main/java/com/payper/domain/user/dto/UserReportResponse.java
  src/main/java/com/payper/domain/user/dto/UserTransactionSummaryDto.java
  src/main/java/com/payper/external/config/HttpConfig.java
  src/main/java/com/payper/external/crawling/service/sub/OpenAIExtractPartnerAndCategoryService.java
  src/main/java/com/payper/external/gpt/OpenAIExtractService.java
  src/main/resources/com/payper/domain/card/mapper/CardMapper.xml
  src/main/resources/com/payper/domain/user/UserCardTransactionMapper.xml
  src/main/resources/sql/data/V3_category_partner.sql
Labels: ✨ Feature

#329 [FEATURE #328]: codef 계정 추가
  src/main/java/com/payper/external/codef/CodefController.java
  src/main/java/com/payper/external/codef/CodefService.java
  src/main/java/com/payper/external/codef/dto/request/AddAccountRequest.java
  src/main/java/com/payper/external/codef/dto/request/CreateAccountRequest.java
  src/main/java/com/payper/external/codef/dto/response/AddAccountResponse.java
  src/main/java/com/payper/external/codef/dto/response/CreateAccountResponse.java
  src/main/java/com/payper/external/codef/exception/ConnectedIdMismatchException.java
Labels: ✨ Feature

#344 [REFACTOR #256]: 카드 상세 조회에서 isMine 필드 추가
  src/main/java/com/payper/domain/card/CardController.java
  src/main/java/com/payper/domain/card/dto/response/CardResponse.java
  src/main/java/com/payper/domain/card/mapper/CardMapper.java
  src/main/java/com/payper/domain/card/service/CardService.java
  src/main/java/com/payper/domain/card/service/SearchService.java
  src/main/java/com/payper/global/config/RootConfig.java
  src/main/java/com/payper/global/security/config/SecurityConfig.java
  src/main/resources/com/payper/domain/card/mapper/CardMapper.xml
  src/main/resources/com/payper/domain/card/mapper/SearchMapper.xml
Labels: ⚒️ Refactor

#346 [BUG #345]: 충돌
  src/main/java/com/payper/domain/card/CardController.java
  src/main/java/com/payper/domain/card/service/SearchService.java
  src/main/java/com/payper/global/config/RootConfig.java
  src/main/resources/com/payper/domain/card/mapper/SearchMapper.xml
Labels: 🐞 Bug

#348 [BUG #347]: mybatis searchmapper.xml 파일 수정
  src/main/java/com/payper/domain/card/CardController.java
  src/main/java/com/payper/domain/card/dto/SearchOptions.java
  src/main/java/com/payper/domain/card/mapper/SearchMapper.java
  src/main/java/com/payper/domain/card/service/SearchService.java
  src/main/java/com/payper/domain/partner/PartnerService.java
  src/main/java/com/payper/global/config/RootConfig.java
  src/main/resources/com/payper/domain/card/mapper/SearchMapper.xml
Labels: 🐞 Bug

#354 [REFACTOR #353]: 시중 카드 검색최적화를 위한 schema 쿼리문 수정. 인덱스 추가
  src/main/resources/com/payper/domain/card/mapper/SearchMapper.xml
  src/main/resources/sql/schema/V3_schema.sql
Labels: ⚒️ Refactor

#358 [REFACTOR #357]: 최근 사용 내역 조회
  src/main/java/com/payper/domain/card/mapper/CardMapper.java
  src/main/java/com/payper/domain/partner/domain/Partner.java
  src/main/java/com/payper/domain/report/ReportController.java
  src/main/java/com/payper/domain/userCardTransaction/UserCardTransactionController.java
  src/main/java/com/payper/domain/userCardTransaction/UserCardTransactionService.java
  src/main/java/com/payper/external/codef/CodefService.java
  src/main/java/com/payper/external/codef/dto/output/ApprovalInfo.java
  src/main/java/com/payper/external/codef/dto/request/ApprovalListRequest.java
  src/main/resources/com/payper/domain/card/mapper/CardMapper.xml
  src/main/resources/com/payper/domain/userCardTransaction/UserCardTransactionMapper.xml
Labels: ⚒️ Refactor
