Repository payper-devs/payper-server, pull requests merged in 2025-07, with the labels that each got.

#12 [DEVOPS #11]: PR 자동 테스트 CI 구성
  .gitattributes
  .github/workflows/ci.yml
  .idea/vcs.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: 🐳 DevOps

#43 [REFACTOR #41]: domain 객체 수정
  .idea/.gitignore
  .idea/dataSources.xml
  .idea/description.html
  .idea/gradle.xml
  .idea/misc.xml
  .idea/project-template.xml
  .idea/template-meta.xml
  .idea/vcs.xml
  src/main/java/com/payper/benefit/domain/Benefit.java
  src/main/java/com/payper/benefit/domain/BenefitGrade.java
  src/main/java/com/payper/benefit/domain/BenefitLimit.java
  src/main/java/com/payper/benefit/domain/Discount.java
  src/main/java/com/payper/benefit/domain/Grade.java
  src/main/java/com/payper/card/domain/AnnualCost.java
  src/main/java/com/payper/card/domain/Card.java
  src/main/java/com/payper/card/domain/Company.java
  src/main/java/com/payper/category/domain/Category.java
  src/main/java/com/payper/category/domain/Partner.java
  src/main/java/com/payper/user/domain/User.java
  src/main/java/com/payper/user/domain/UserCard.java
  src/main/java/com/payper/user/domain/UserCardMonthAmount.java
Labels: ⚒️ Refactor

#51 [CHORE #50]: application.properties 수정
  .gitignore
  src/main/java/com/payper/config/RootConfig.java
  src/main/resources/application.properties
Labels: 🧹 Chore

#54 [REFACTOR #53]: 도메인 객체 수정
  src/main/java/com/payper/benefit/domain/Benefit.java
  src/main/java/com/payper/benefit/domain/BenefitGrade.java
  src/main/java/com/payper/benefit/domain/BenefitGradeDiscount.java
  src/main/java/com/payper/benefit/domain/BenefitLimit.java
  src/main/java/com/payper/benefit/domain/Discount.java
  src/main/java/com/payper/benefit/domain/DiscountType.java
  src/main/java/com/payper/benefit/domain/Grade.java
  src/main/java/com/payper/card/domain/AnnualCost.java
  src/main/java/com/payper/card/domain/Card.java
  src/main/java/com/payper/card/domain/CardType.java
  src/main/java/com/payper/card/domain/Company.java
  src/main/java/com/payper/category/domain/BenefitCategory.java
  src/main/java/com/payper/category/domain/Category.java
  src/main/java/com/payper/user/domain/User.java
  src/main/java/com/payper/user/domain/UserCardMonthAmount.java
Labels: ⚒️ Refactor

#59 [REFACTOR #58]: schema.sql 수정
  src/main/resources/sql/schema.sql
Labels: ⚒️ Refactor

#62 [FEATURE #47]: CODEF connected id 연동 및 보유 카드 목록 불러오기
  .gitignore
  build.gradle
  src/main/java/com/payper/codef/controller/CodefController.java
  src/main/java/com/payper/codef/dto/output/CardInfo.java
  src/main/java/com/payper/codef/dto/output/CodefStandardResponse.java
  src/main/java/com/payper/codef/dto/output/ErrorItem.java
  src/main/java/com/payper/codef/dto/output/Result.java
  src/main/java/com/payper/codef/dto/output/SuccessItem.java
  src/main/java/com/payper/codef/dto/request/ConnectedIdRequest.java
  src/main/java/com/payper/codef/dto/request/MyCardListRequest.java
  src/main/java/com/payper/codef/dto/response/ConnectedIdResponse.java
  src/main/java/com/payper/codef/dto/response/MyCardListResponse.java
  src/main/java/com/payper/codef/service/CodefService.java
  src/main/java/com/payper/codef/util/OrganizationCode.java
  src/main/java/com/payper/config/CodefConfig.java
  src/main/java/com/payper/config/RootConfig.java
  src/main/java/com/payper/config/ServletConfig.java
  src/main/java/com/payper/security/config/SecurityConfig.java
  src/main/java/com/payper/user/dto/UserResponse.java
  src/main/java/com/payper/user/mapper/UserMapper.java
  src/main/java/com/payper/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/com/payper/user/mapper/UserMapper.xml
Labels: ✨ Feature

#63 [REFACTOR #61]: 카드 및 혜택 데이터 CRAWLING 변경
  src/main/java/com/payper/crawling/CardJsonCrawler.java
  src/main/java/com/payper/crawling/CardJsonExtractor.java
Labels: ⚒️ Refactor

#67 [FEATURE #60]: LLM 기반 SQL Insert 생성 설정
  src/main/java/com/payper/openai/GptConfig.java
  src/main/java/com/payper/openai/OpenAISqlGenerator.java
Labels: ✨ Feature

#70 [REFACTOR #65]: 도메인 객체 및 응답 객체 수정
  src/main/java/com/payper/benefit/domain/Benefit.java
  src/main/java/com/payper/benefit/domain/BenefitGradeDiscount.java
  src/main/java/com/payper/benefit/domain/Grade.java
  src/main/java/com/payper/benefit/dto/BenefitGradeResponse.java
  src/main/java/com/payper/benefit/dto/BenefitResponse.java
  src/main/java/com/payper/benefit/dto/DiscountResponse.java
  src/main/java/com/payper/benefit/dto/LimitResponse.java
  src/main/java/com/payper/card/domain/Card.java
  src/main/java/com/payper/card/dto/AnnualCostResponse.java
  src/main/java/com/payper/card/dto/CardCompanyResponse.java
  src/main/java/com/payper/card/dto/CardResponse.java
  src/main/java/com/payper/category/domain/BenefitCategory.java
  src/main/java/com/payper/category/domain/Category.java
  src/main/java/com/payper/category/dto/CategoryResponse.java
  src/main/java/com/payper/category/dto/PartnerResponse.java
  src/main/java/com/payper/exception/CustomException.java
  src/main/java/com/payper/exception/ErrorResponse.java
  src/main/java/com/payper/exception/GlobalExceptionHandler.java
  src/main/java/com/payper/exception/TemplateException.java
  src/main/java/com/payper/user/domain/User.java
  src/main/java/com/payper/user/domain/UserCard.java
  src/main/java/com/payper/user/domain/UserCardMonthAmount.java
  src/main/resources/application.properties
Labels: ⚒️ Refactor

#75 [FEATURE #71]: 시중카드 리스트 조회
  src/main/java/com/payper/card/controller/CardController.java
  src/main/java/com/payper/card/mapper/CardMapper.java
  src/main/java/com/payper/card/service/CardService.java
  src/main/java/com/payper/config/RootConfig.java
  src/main/java/com/payper/config/ServletConfig.java
  src/main/resources/com/payper/card/mapper/CardMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/resources/sql/card2.sql
  src/main/resources/sql/schema.sql
Labels: ✨ Feature

#79 [FEATURE #77]: 각 시중카드 조회
  src/main/java/com/payper/card/controller/CardController.java
  src/main/java/com/payper/card/exception/CardNotFoundException.java
  src/main/java/com/payper/card/mapper/CardMapper.java
  src/main/java/com/payper/card/service/CardService.java
  src/main/java/com/payper/exception/ApiExceptionAdvice.java
  src/main/java/com/payper/exception/CommonExceptionAdvice.java
  src/main/java/com/payper/exception/GlobalExceptionHandler.java
  src/main/java/com/payper/exception/TemplateException.java
  src/main/resources/com/payper/card/mapper/CardMapper.xml
Labels: ✨ Feature

#69 [FEATURE #56]: Spring Security 인증 구현
  build.gradle
  src/main/java/com/payper/config/RootConfig.java
  src/main/java/com/payper/config/ServletConfig.java
  src/main/java/com/payper/exception/GlobalExceptionHandler.java
  src/main/java/com/payper/security/KakaoLoginRequest.java
  src/main/java/com/payper/security/LoginResponse.java
  src/main/java/com/payper/security/config/SecurityConfig.java
  src/main/java/com/payper/security/controller/AuthController.java
  src/main/java/com/payper/security/domain/CustomUser.java
  src/main/java/com/payper/security/dto/KakaoLoginRequest.java
  src/main/java/com/payper/security/dto/LoginResponse.java
  src/main/java/com/payper/security/filter/AuthenticationErrorFilter.java
  src/main/java/com/payper/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/payper/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/payper/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/payper/security/handler/LoginFailureHandler.java
  src/main/java/com/payper/security/handler/LoginSuccessHandler.java
  src/main/java/com/payper/security/mapper/UserDetailsMapper.java
  src/main/java/com/payper/security/service/AuthService.java
  src/main/java/com/payper/security/service/CustomUserDetailsService.java
  src/main/java/com/payper/security/util/JsonResponse.java
  src/main/java/com/payper/security/util/JwtProcessor.java
  src/main/java/com/payper/security/util/OAuthProvider.java
  src/main/java/com/payper/user/domain/User.java
  src/main/java/com/payper/user/domain/UserAuth.java
  src/main/java/com/payper/user/mapper/UserMapper.java
  src/main/resources/com.payper.security.mapper/UserDetailsMapper.xml
  src/main/resources/com/payper/user/mapper/UserMapper.xml
  src/main/resources/sql/schema.sql
  src/main/resources/sql/user.sql
Labels: ⚒️ Refactor, ✨ Feature

#87 [FEATURE #68]: 크롤링된 JSON 기반 정제
  build.gradle
  src/main/java/com/payper/crawling/CardBenefitCleaner.java
  src/main/java/com/payper/crawling/CardJsonCrawler.java
  src/main/java/com/payper/crawling/CardJsonExtractor.java
  src/main/java/com/payper/crawling/dto/CardData.java
  src/main/java/com/payper/openai/OpenAISqlGenerator.java
Labels: ✨ Feature

#86 [FEATURE #78]: 시중 카드 검색 API
  src/main/java/com/payper/card/controller/CardController.java
  src/main/java/com/payper/card/mapper/CardMapper.java
  src/main/java/com/payper/card/service/CardService.java
  src/main/resources/com/payper/card/mapper/CardMapper.xml
Labels: ✨ Feature

#93 [FEATURE #76]: 내카드 리스트 조회
  src/main/java/com/payper/card/controller/CardController.java
  src/main/java/com/payper/card/mapper/CardMapper.java
  src/main/java/com/payper/card/service/CardService.java
  src/main/java/com/payper/security/config/SecurityConfig.java
  src/main/java/com/payper/security/domain/CustomUser.java
  src/main/java/com/payper/security/util/JwtProcessor.java
  src/main/java/com/payper/user/controller/UserController.java
  src/main/resources/com/payper/card/mapper/CardMapper.xml
  src/main/resources/com/payper/security/mapper/UserDetailsMapper.xml
  src/main/resources/sql/user.sql
Labels: ⚒️ Refactor, ✨ Feature

#94 [FEATURE #74]: 내 카드로 등록
  src/main/java/com/payper/card/controller/CardController.java
  src/main/java/com/payper/card/dto/RegisterCardMeRequest.java
  src/main/java/com/payper/card/mapper/CardMapper.java
  src/main/java/com/payper/card/service/CardService.java
  src/main/java/com/payper/user/service/UserService.java
  src/main/resources/com/payper/card/mapper/CardMapper.xml
  ãUserService로
Labels: ✨ Feature

#103 [REFACTOR #83-1]: Domain -> DTO(Response) 변환 로직 리팩토링
  src/main/java/com/payper/domain/benefit/dto/BenefitResponse.java
Labels: ⚒️ Refactor
